sudo: false
dist: trusty

language: node_js

cache:
    yarn: true
    directories:
    - node_modules

matrix:
    fast_finish: true
    include:
    -   node_js: '6'
        env: TARGET=lint
    -   node_js: '6'
        env: TARGET=build
    -   node_js: '6'
        env: TARGET=test
    -   node_js: '8'
        env: TARGET=test
    -   node_js: '9'
        env: TARGET=test
    -   node_js: '10'
        env: TARGET=test

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH=$HOME/.yarn/bin:$PATH

before_script: yarn install

script: yarn run $TARGET
